<a href="https://colab.research.google.com/github/shnakshi090/Python/blob/main/numpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Load the NumPy

import numpy as np
arravali = np.array(np.random.randint(10,45,(8,2)))
print(f"The defined array is \n{arravali}")
print(f" \n The shape of the array is {arravali.shape}")


The defined array is 
[[18 36]
 [31 30]
 [20 26]
 [16 40]
 [13 25]
 [42 22]
 [19 19]
 [21 44]]
 
 The shape of the array is (8, 2)


In [3]:
#Storing the transpose in another matrix object

nilgiri = np.transpose(arravali)
print(f" This transpose of the array is \n{nilgiri}")
print(f" \n The shape of the array is {nilgiri.shape}")


 This transpose of the array is 
[[18 31 20 16 13 42 19 21]
 [36 30 26 40 25 22 19 44]]
 
 The shape of the array is (2, 8)


In [4]:
#3D Array

random_3d_array = np.array(np.random.randint(10,45,(3,2,4)))
print(f"The defined array is \n{random_3d_array}")
print(f" \n The shape of the array is {random_3d_array.shape}")

The defined array is 
[[[15 10 28 28]
  [17 28 35 23]]

 [[26 37 42 29]
  [22 32 27 43]]

 [[42 40 11 39]
  [33 26 25 41]]]
 
 The shape of the array is (3, 2, 4)


In [5]:
#Storing the transpose of the created 3D Array

transpose_3d_array = np.transpose(random_3d_array)
print(f" This transpose of the array is \n{transpose_3d_array}")
print(f" \n The shape of the array is {transpose_3d_array.shape}")

 This transpose of the array is 
[[[15 26 42]
  [17 22 33]]

 [[10 37 40]
  [28 32 26]]

 [[28 42 11]
  [35 27 25]]

 [[28 29 39]
  [23 43 41]]]
 
 The shape of the array is (4, 2, 3)


In [6]:
#Create a two dimensional array

random_cohort = np.array(np.random.randint(10,45,(3,8)))
print(f"The defined array is \n{random_cohort}")
print(f" \n The shape of the array is {random_cohort.shape}")

The defined array is 
[[28 34 30 30 35 31 38 28]
 [39 30 34 14 44 40 10 34]
 [11 24 21 44 20 32 20 16]]
 
 The shape of the array is (3, 8)


In [7]:
#Now we can reshape this to 1D,2D or 3D Array

new_shape = (2,6,2)
reshaped_random_cohort = np.reshape(random_cohort,new_shape)
print(f"This reshaped array is \n{reshaped_random_cohort}")
print(f" \n The shape of the array is {reshaped_random_cohort.shape}")

This reshaped array is 
[[[28 34]
  [30 30]
  [35 31]
  [38 28]
  [39 30]
  [34 14]]

 [[44 40]
  [10 34]
  [11 24]
  [21 44]
  [20 32]
  [20 16]]]
 
 The shape of the array is (2, 6, 2)


In [8]:
new_shape = (2,-1,6)
reshaped_random_cohort = np.reshape(random_cohort,new_shape)
print(f"This reshaped array is \n{reshaped_random_cohort}")
print(f" \n The shape of the array is {reshaped_random_cohort.shape}")

This reshaped array is 
[[[28 34 30 30 35 31]
  [38 28 39 30 34 14]]

 [[44 40 10 34 11 24]
  [21 44 20 32 20 16]]]
 
 The shape of the array is (2, 2, 6)


In [9]:
random_3D_cohort = np.array(np.random.randint(10,45,(3,6,2)))
print(f"The defined array is \n{random_3D_cohort}")
print(f" \n The shape of the array is {random_3D_cohort.shape}")

The defined array is 
[[[14 37]
  [27 30]
  [39 11]
  [31 31]
  [42 19]
  [41 17]]

 [[21 35]
  [28 14]
  [21 31]
  [33 43]
  [33 36]
  [42 41]]

 [[10 24]
  [24 15]
  [20 41]
  [31 21]
  [43 14]
  [10 14]]]
 
 The shape of the array is (3, 6, 2)


In [10]:
new_shape = (2,1,6)
resize_random_3D_cohort = np.resize(random_3D_cohort,new_shape)
print(f"This resized array is \n{resize_random_3D_cohort}")
print(f" \n The shape of the array is {resize_random_3D_cohort.shape}")

This resized array is 
[[[14 37 27 30 39 11]]

 [[31 31 42 19 41 17]]]
 
 The shape of the array is (2, 1, 6)


In [11]:
random_3D_cohort = np.array(np.random.randint(10,45,(2,4,6)))
print(f"The defined array is \n{random_3D_cohort}")
print(f" \n The shape of the array is {random_3D_cohort.shape}")

The defined array is 
[[[42 26 18 26 12 11]
  [32 18 31 40 29 15]
  [23 14 27 21 17 16]
  [15 27 10 34 29 24]]

 [[42 43 35 36 38 35]
  [15 26 40 41 23 37]
  [27 22 16 22 32 25]
  [39 33 36 19 19 16]]]
 
 The shape of the array is (2, 4, 6)


In [12]:
new_shape = (2,3,6)
resized_random_3D_cohort = np.resize(random_3D_cohort,new_shape)
print(f"This resized array is \n{resize_random_3D_cohort}")
print(f" \n The shape of the array is {resize_random_3D_cohort.shape}")

This resized array is 
[[[14 37 27 30 39 11]]

 [[31 31 42 19 41 17]]]
 
 The shape of the array is (2, 1, 6)


In [13]:
import numpy as np
random_3D_cohort = np.array(np.random.randint(10,45,(2,4,6)))
print(f"The defined array is \n{random_3D_cohort}")
print(f" \n The shape of the array is {random_3D_cohort.shape}")

The defined array is 
[[[21 44 18 22 33 37]
  [32 40 39 40 44 16]
  [17 24 44 22 40 39]
  [17 26 24 38 43 41]]

 [[22 43 21 17 23 10]
  [31 10 27 19 40 27]
  [22 36 25 36 23 13]
  [21 33 26 31 20 31]]]
 
 The shape of the array is (2, 4, 6)


In [14]:
new_shape = (2,3,6)
resized_random_3D_cohort = np.resize(random_3D_cohort,new_shape)
print(f"This resized array is \n{resized_random_3D_cohort}")
print(f" \n The shape of the array is {resized_random_3D_cohort.shape}")

This resized array is 
[[[21 44 18 22 33 37]
  [32 40 39 40 44 16]
  [17 24 44 22 40 39]]

 [[17 26 24 38 43 41]
  [22 43 21 17 23 10]
  [31 10 27 19 40 27]]]
 
 The shape of the array is (2, 3, 6)


In [15]:
import numpy as np
a = np.random.randint(10,20,(2,3,4))   #Axis 0-2 ; Axis 1-3 ; Axis 2-4
print(a)
print(a.shape)

[[[13 10 16 13]
  [13 13 10 17]
  [18 12 15 13]]

 [[14 19 14 10]
  [19 15 11 18]
  [12 14 17 19]]]
(2, 3, 4)


In [16]:
#Insert along axis = 0
np.insert(a,1,100,axis=0)

array([[[ 13,  10,  16,  13],
        [ 13,  13,  10,  17],
        [ 18,  12,  15,  13]],

       [[100, 100, 100, 100],
        [100, 100, 100, 100],
        [100, 100, 100, 100]],

       [[ 14,  19,  14,  10],
        [ 19,  15,  11,  18],
        [ 12,  14,  17,  19]]])

In [17]:
a = np.random.randint(2,6,(2,3,3))
print(a)
print(a.shape)

[[[2 5 5]
  [2 5 3]
  [2 5 3]]

 [[5 4 4]
  [4 3 3]
  [5 4 2]]]
(2, 3, 3)


In [18]:
np.append(a,50)

array([ 2,  5,  5,  2,  5,  3,  2,  5,  3,  5,  4,  4,  4,  3,  3,  5,  4,
        2, 50])

In [19]:
b = np.random.randint(2,6,(2,1,3))
print(b)

[[[5 2 4]]

 [[3 3 2]]]


In [20]:
print(a)
print(a.shape)


[[[2 5 5]
  [2 5 3]
  [2 5 3]]

 [[5 4 4]
  [4 3 3]
  [5 4 2]]]
(2, 3, 3)


In [21]:
np.append(a,b,axis=1)

array([[[2, 5, 5],
        [2, 5, 3],
        [2, 5, 3],
        [5, 2, 4]],

       [[5, 4, 4],
        [4, 3, 3],
        [5, 4, 2],
        [3, 3, 2]]])

In [22]:
import numpy as np
a = np.random.randint(2,6,(2,3,3))
print(a)
print(a.shape)


[[[4 5 4]
  [5 2 2]
  [4 3 5]]

 [[3 4 4]
  [2 2 3]
  [3 3 2]]]
(2, 3, 3)


In [23]:
np.delete(a,(0),axis = 0)

array([[[3, 4, 4],
        [2, 2, 3],
        [3, 3, 2]]])

In [24]:
np.delete(a,(0,2),axis = 1)

array([[[5, 2, 2]],

       [[2, 2, 3]]])

In [25]:
a

array([[[4, 5, 4],
        [5, 2, 2],
        [4, 3, 5]],

       [[3, 4, 4],
        [2, 2, 3],
        [3, 3, 2]]])

In [26]:
np.delete(a,(0,1),axis = 2)

array([[[4],
        [2],
        [5]],

       [[4],
        [3],
        [2]]])

In [27]:
a = np.random.randint(2,20,(2,3,3))
print(a)
print(a.shape)


[[[15 19 17]
  [14  6 13]
  [15  4 14]]

 [[ 8  8  8]
  [11 16 16]
  [13  7  6]]]
(2, 3, 3)


In [28]:
np.unique(a)

array([ 4,  6,  7,  8, 11, 13, 14, 15, 16, 17, 19])

In [29]:
np.unique(a,return_counts=True)

(array([ 4,  6,  7,  8, 11, 13, 14, 15, 16, 17, 19]),
 array([1, 2, 1, 3, 1, 2, 2, 2, 2, 1, 1]))

In [30]:
np.unique(a,return_counts=True,return_index=True)

(array([ 4,  6,  7,  8, 11, 13, 14, 15, 16, 17, 19]),
 array([ 7,  4, 16,  9, 12,  5,  3,  0, 13,  2,  1]),
 array([1, 2, 1, 3, 1, 2, 2, 2, 2, 1, 1]))

In [31]:
a = [1,2,3]
b= a
b[0] = 10
print(b)
print(a)

[10, 2, 3]
[10, 2, 3]


In [32]:
a = np.array([2,34,12])
b = a
b[0] = -999
print(b)
print(a)


[-999   34   12]
[-999   34   12]


In [33]:
a = np.array([2,34,12])
b = a.copy()
b[0] = -999
print(b)
print(a)

[-999   34   12]
[ 2 34 12]


In [34]:
np.arange(3) + 5

array([5, 6, 7])

In [35]:
np.ones((3,3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [36]:
np.arange(3).reshape((3,1)) + np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [37]:
np.arange(2)

array([0, 1])

In [38]:
a = np.random.randint(2,6,(2,4))
print(a)
b = np.random.randint(1,10,(2,2))
print(b)

[[4 2 5 5]
 [3 2 4 5]]
[[5 8]
 [7 9]]


In [39]:
a = np.random.randint(2,6,(2,4))
print(a)
b = np.random.randint(0,5,(2,4))
print(b)


[[2 3 5 3]
 [5 5 2 2]]
[[4 3 0 0]
 [1 3 3 4]]


In [40]:
np.multiply(a,b)

array([[ 8,  9,  0,  0],
       [ 5, 15,  6,  8]])

In [41]:
np.divide(a,b)

<ipython-input-41-c364992e28ce>:1: RuntimeWarning: divide by zero encountered in divide
  np.divide(a,b)


array([[0.5       , 1.        ,        inf,        inf],
       [5.        , 1.66666667, 0.66666667, 0.5       ]])

In [42]:
a=np.random.randint(5,9,(2,4))
print(a)

[[8 5 5 6]
 [5 8 7 5]]


In [43]:
print(np.sum(a))
print(np.sum(a,axis = 0))
print(np.sum(a,axis = 1))



49
[13 13 12 11]
[24 25]


In [44]:
print(np.min(a))
print(np.min(a,axis=1)) #Across Column
a =np.random.randint(0,20,(3,3))
print(a)

5
[5 5]
[[ 7 11  7]
 [ 4 17  8]
 [ 8  3 15]]


In [45]:
print(np.sort(a,axis=0)) # Ascending

[[ 4  3  7]
 [ 7 11  8]
 [ 8 17 15]]


In [46]:
print(np.sort(a,axis=1))

[[ 7  7 11]
 [ 4  8 17]
 [ 3  8 15]]


In [47]:
print(-np.sort(-a,axis=1)) #Descending

[[11  7  7]
 [17  8  4]
 [15  8  3]]


In [48]:
sum(np.arange(3)*np.arange(3).transpose())

5